
export const locales = {
  en: {
    // Welcome
    'welcome.title': 'Welcome, Grown-ups!',
    'welcome.p1': 'This is an AI-powered storyteller. The stories and images are generated by AI and can sometimes be unpredictable.',
    'welcome.p2': 'We strongly recommend co-reading with your child to share the magic and guide the experience.',
    'welcome.button': 'I Understand, Let\'s Begin!',

    // Input Screen
    'input.title': 'Create a Magical Story',
    'input.prompt.placeholder': 'A brave little squirrel who wants to fly...',
    'input.inspiration': 'Need inspiration?',
    'input.visualInspiration.label': 'Visual Inspiration (Optional)',
    'input.visualInspiration.description': 'Upload a drawing or photo of your character!',
    'input.visualInspiration.button': 'Upload Image',
    'input.visualInspiration.change': 'Change Image',
    'input.character.title': 'Create a Character (Optional)',
    'input.character.name': 'Name',
    'input.character.type': 'Type (e.g., a brave lion)',
    'input.character.personality': 'Personality (e.g., curious and kind)',
    'input.options.title': 'Customize Your Story',
    'input.options.age': 'Age Group',
    'input.options.theme': 'Theme',
    'input.options.length': 'Length',
    'input.options.style': 'Illustration Style',
    'input.button.create': 'Create My Story!',

    // Loading Screen
    'loading.dreaming': 'Dreaming up characters...',
    'loading.building': 'Building a magical world...',
    'loading.painting': 'Painting the pictures...',
    'loading.finishing': 'Adding the final sparkles...',
    'loading.generatingPage': 'Generating page {currentPage} of {totalPages}...',
    'loading.illustratingPage': 'Illustrating page {currentPage} of {totalPages}...',

    // Story Viewer
    'story.readAloud': 'Read Aloud',
    'story.newStory': 'Create New Story',

    // Error
    'error.title': 'Oh no, a hiccup in the magic!',
    'error.generic': 'Something went wrong while creating the story. Please try again.',

    // Common
    'common.tryAgain': 'Try Again',

    // Options
    'age.3-5': '3-5 years',
    'age.6-8': '6-8 years',
    'theme.friendship': 'Friendship',
    'theme.courage': 'Courage',
    'theme.kindness': 'Being Kind',
    'theme.adventure': 'Adventure',
    'length.short': 'Short (3-4 pages)',
    'length.medium': 'Medium (5-6 pages)',
    'length.long': 'Long (7-8 pages)',
    'style.watercolor': 'Watercolor',
    'style.cartoon': 'Cartoon',
    'style.pixel': 'Pixel Art',
    'style.fantasy': 'Fantasy',

    // Sample Prompts
    'prompt.sample1': 'A curious cat who finds a magic hat',
    'prompt.sample2': 'A friendly robot who wants to plant a garden',
    'prompt.sample3': 'A little ghost who is afraid of the dark',
    'prompt.sample4': 'Two best friend dinosaurs who find a treasure map',
  },
  id: {
    // Welcome
    'welcome.title': 'Selamat Datang, Para Orang Dewasa!',
    'welcome.p1': 'Ini adalah pendongeng yang didukung AI. Cerita dan gambar dibuat oleh AI dan terkadang tidak dapat diprediksi.',
    'welcome.p2': 'Kami sangat menyarankan untuk membaca bersama anak Anda untuk berbagi keajaiban dan memandu pengalaman.',
    'welcome.button': 'Saya Mengerti, Mari Mulai!',

    // Input Screen
    'input.title': 'Buat Cerita Ajaib',
    'input.prompt.placeholder': 'Seekor tupai kecil pemberani yang ingin terbang...',
    'input.inspiration': 'Butuh inspirasi?',
    'input.visualInspiration.label': 'Inspirasi Visual (Opsional)',
    'input.visualInspiration.description': 'Unggah gambar atau foto karakter Anda!',
    'input.visualInspiration.button': 'Unggah Gambar',
    'input.visualInspiration.change': 'Ganti Gambar',
    'input.character.title': 'Buat Karakter (Opsional)',
    'input.character.name': 'Nama',
    'input.character.type': 'Jenis (misalnya, singa pemberani)',
    'input.character.personality': 'Kepribadian (misalnya, ingin tahu dan baik hati)',
    'input.options.title': 'Sesuaikan Cerita Anda',
    'input.options.age': 'Kelompok Usia',
    'input.options.theme': 'Tema',
    'input.options.length': 'Panjang',
    'input.options.style': 'Gaya Ilustrasi',
    'input.button.create': 'Buat Ceritaku!',

    // Loading Screen
    'loading.dreaming': 'Memimpikan karakter...',
    'loading.building': 'Membangun dunia magis...',
    'loading.painting': 'Melukis gambar...',
    'loading.finishing': 'Menambahkan kilauan terakhir...',
    'loading.generatingPage': 'Membuat halaman {currentPage} dari {totalPages}...',
    'loading.illustratingPage': 'Mengilustrasikan halaman {currentPage} dari {totalPages}...',

    // Story Viewer
    'story.readAloud': 'Bacakan',
    'story.newStory': 'Buat Cerita Baru',

    // Error
    'error.title': 'Oh tidak, ada gangguan dalam sihir!',
    'error.generic': 'Terjadi kesalahan saat membuat cerita. Silakan coba lagi.',

    // Common
    'common.tryAgain': 'Coba Lagi',

    // Options
    'age.3-5': '3-5 tahun',
    'age.6-8': '6-8 tahun',
    'theme.friendship': 'Persahabatan',
    'theme.courage': 'Keberanian',
    'theme.kindness': 'Kebaikan',
    'theme.adventure': 'Petualangan',
    'length.short': 'Pendek (3-4 halaman)',
    'length.medium': 'Sedang (5-6 halaman)',
    'length.long': 'Panjang (7-8 halaman)',
    'style.watercolor': 'Cat Air',
    'style.cartoon': 'Kartun',
    'style.pixel': 'Pixel Art',
    'style.fantasy': 'Fantasi',

    // Sample Prompts
    'prompt.sample1': 'Kucing penasaran yang menemukan topi ajaib',
    'prompt.sample2': 'Robot ramah yang ingin menanam kebun',
    'prompt.sample3': 'Hantu kecil yang takut gelap',
    'prompt.sample4': 'Dua sahabat dinosaurus yang menemukan peta harta karun',
  }
};
